sudo: false
dist: bionic
language: python
cache: pip

addons:
  apt:
    packages:
    - pandoc

python:
- 3.6
- 3.7
- 3.8
- pypy3

jobs:
  allow_failures:
  - python: pypy3

before_install:
- pip install -r ci/requirements.txt

install:
- pip install .

script:
- python    -m coverage run -p --source=pronto -m unittest discover -v
- python -O -m coverage run -p --source=pronto -m unittest discover -v

after_success:
- coverage combine
- coverage xml --include "pronto/*"
- codecov
- python-codacy-coverage -r coverage.xml

before_deploy:
- python setup.py sdist bdist_wheel
- twine check dist/*

deploy:
- provider: script
  script: twine upload --skip-existing dist/*
  skip_cleanup: true
  on:
    python: "3.7"
    tags: true
    repo: althonos/pronto
- provider: script
  script: ci/travis/chandler.sh
  on:
    python: "3.7"
    repo: althonos/pronto

notifications:
  email:
  - althonosdev@gmail.com
