sudo: false
language: python
cache: pip

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
- 'pypy3'

matrix:
  allow_failures:
  - python: 'pypy'
  - python: 'pypy3'

before_install:
- pip install -U wheel setuptools pip
- pip install -r requirements.txt -r tests/requirements.txt

install:
- pip install .

script:
- coverage run --source=pronto -m unittest discover -v
- coverage combine
- coverage xml --include "pronto/*"

after_success:
- codecov
- python-codacy-coverage -r xml

before_deploy:
- python setup.py sdist --formats zip,gztar bdist_wheel
- python setup.py check -rms

deploy:
- provider: pypi
  user: althonos
  password:
    secure: tOxmKL2WfIajsSao4rVau9xLehIqfpKOm9SCwUlGREJas/D+yFYcltdamVa/kpc2PgHcmQBJxkZzEEDsAiZunm/435qWR2T01B2zB00JdtfWvnoCWEEzg/SEsy/0yS6m666P3vbdSvtfHByaavzPf5RE3ooBwsbKt3OKgS3fs91zFZwJZU6zATpBC6pzwhbt6PZeYzmZnk2AkRl8O2abPh8iHz1DGxJ3baY3ObG289W5Dp9a3sr9PVkXvLCMe04JeORTlPt43hnAy6PpnN8FSgKKLdTiMeqRcctZdH8Y90EIW8nWWoqaokNVLepxDDtf3ouy57DNyZu1FNZDlsQd7aYyUrydy7UIrMa33L7ai0hRcvKQI1ymRbO3W4opOPDcORulvYGUNLeVU886lvuLavlJ+otZClRBPV3EuO0k2eslAvwiTF8DBjB9HPuF3ZtkBgnDH7ubU1hoMi6MQvbjVThI0J7uyTVNmnS8r9/Yv02TsTl+IBHzhE3Sb8z2ZNF/Ip5UU5rbcmmvA/euShL2A+Eb0hhe/Fen3fVROl/cwcGIbkEXTurzc5xfyoLs76VOxr+HvYqA4DzxvDwhhvQSk0PTymO5T5WRj4PYbmkHeevVCsH8unva27u1CeKhVYIrWyvXwDhIK11mLzWKT2SAEVypil8YUcQpROR8vJP2yA4=
  distributions: sdist bdist_wheel
  on:
    python: '3.6'
    tags: true
    repo: althonos/pronto
  server: https://upload.pypi.org/legacy/

notifications:
  email:
  - althonosdev@gmail.com
