sudo: false
dist: xenial
language: python
cache: pip

python:
- 3.6
- 3.7
- pypy3

before_install:
- pip install -r ci/requirements.txt

install:
- pip install .

script:
- coverage run --source=pronto -m unittest discover -v
- coverage xml --include "pronto/*"

after_success:
- codecov
- python-codacy-coverage -r coverage.xml

before_deploy:
- python setup.py sdist bdist_wheel
- twine check dist/*

deploy:
  provider: script
  script: twine upload --skip-existing dist/*
  skip_cleanup: true
  on:
    python: "3.7"
    tags: true
    repo: althonos/pronto

notifications:
  email:
  - althonosdev@gmail.com
